[workspace]
members = [
    "examples/linear_regression",
    "fhe",
    "vm",
    "air",
    "prover"
]

resolver = "2"

[workspace.dependencies]
bincode = { version = "1.3.3" }
winterfell = { version = "0.9.0" }
tempfile = { version = "3.12.0" }
