[workspace]
members = [ "examples/linear_regression",
    "fhe",
    "vm"
]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0", features = ["derive"] }
bincode = { version = "1.3.3" }
