[package]
name = "vm"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
fhe = { path = "../fhe" }
winterfell = { workspace = true }
prover = { path = "../prover"}

[dev-dependencies]
tempfile = { version = "3.12.0" }