[package]
name = "linear_regression"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = { workspace = true }
winterfell = { workspace = true }
fhe = { path = "../../fhe" }
vm = { path = "../../vm" }
air = { path = "../../air" }
crypto = { path = "../../crypto" }