[package]
name = "fhe"
version = "0.1.0"
edition = "2021"

[dependencies]
rand_distr = "0.4"
rand = { workspace = true }
winterfell = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
