name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  continuous-integration:
    name: Continuous Integration
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Clippy Check
      run: cargo clippy --all-targets --all-features

    - name: Format Check
      run: cargo fmt --check

    - name: Build
      run: cargo build --verbose

    - name: Test
      run: cargo test --verbose